"""Witness candidate primitives for proactive Kortny behavior."""

from kortny.witness.extractor import (
    WITNESS_CHANNEL_PROFILE_EXTRACTOR_PROMPT_NAME,
    WITNESS_CHANNEL_PROFILE_EXTRACTOR_RESPONSE_FORMAT,
    WITNESS_TASK_RESPONSE_EXTRACTOR_PROMPT_NAME,
    WITNESS_TASK_RESPONSE_EXTRACTOR_RESPONSE_FORMAT,
    WitnessChannelProfileExtractor,
    WitnessTaskResponseExtraction,
    WitnessTaskResponseExtractor,
    parse_witness_channel_profile_extraction,
    parse_witness_task_response_extraction,
)
from kortny.witness.lifecycle import (
    DEFAULT_WITNESS_SNOOZE,
    WITNESS_SUGGESTION_PURPOSE,
    WitnessDeliveryResult,
    accept_candidate,
    archive_candidate,
    dismiss_candidate,
    reactivate_candidate,
    send_private_suggestion,
    snooze_candidate,
)
from kortny.witness.opportunities import (
    ALLOWED_CANDIDATE_TYPES,
    WITNESS_OPPORTUNITY_CANDIDATES_PROJECTED_MESSAGE,
    WitnessOpportunityCandidateInput,
    WitnessOpportunityCandidateResult,
    WitnessOpportunityService,
)
from kortny.witness.runner import (
    DEFAULT_WITNESS_DELIVERY_LIMIT,
    DEFAULT_WITNESS_PROFILE_SCAN_LIMIT,
    DEFAULT_WITNESS_SCAN_INTERVAL,
    WITNESS_RUNNER_DELIVERY_SENT_MESSAGE,
    WITNESS_RUNNER_DELIVERY_SKIPPED_MESSAGE,
    WITNESS_RUNNER_PROFILE_SCAN_COMPLETED_MESSAGE,
    WITNESS_RUNNER_PROFILE_SCAN_FAILED_MESSAGE,
    WITNESS_RUNNER_PROFILE_SCAN_STARTED_MESSAGE,
    WitnessDeliveryOutcome,
    WitnessProjectionOutcome,
    WitnessRunner,
    WitnessRunResult,
    WitnessWorker,
)

__all__ = [
    "ALLOWED_CANDIDATE_TYPES",
    "WITNESS_CHANNEL_PROFILE_EXTRACTOR_PROMPT_NAME",
    "WITNESS_CHANNEL_PROFILE_EXTRACTOR_RESPONSE_FORMAT",
    "WITNESS_SUGGESTION_PURPOSE",
    "WITNESS_TASK_RESPONSE_EXTRACTOR_PROMPT_NAME",
    "WITNESS_TASK_RESPONSE_EXTRACTOR_RESPONSE_FORMAT",
    "WITNESS_OPPORTUNITY_CANDIDATES_PROJECTED_MESSAGE",
    "WITNESS_RUNNER_DELIVERY_SENT_MESSAGE",
    "WITNESS_RUNNER_DELIVERY_SKIPPED_MESSAGE",
    "WITNESS_RUNNER_PROFILE_SCAN_COMPLETED_MESSAGE",
    "WITNESS_RUNNER_PROFILE_SCAN_FAILED_MESSAGE",
    "WITNESS_RUNNER_PROFILE_SCAN_STARTED_MESSAGE",
    "DEFAULT_WITNESS_SNOOZE",
    "DEFAULT_WITNESS_DELIVERY_LIMIT",
    "DEFAULT_WITNESS_PROFILE_SCAN_LIMIT",
    "DEFAULT_WITNESS_SCAN_INTERVAL",
    "WitnessDeliveryResult",
    "WitnessDeliveryOutcome",
    "WitnessOpportunityCandidateInput",
    "WitnessOpportunityCandidateResult",
    "WitnessOpportunityService",
    "WitnessProjectionOutcome",
    "WitnessRunResult",
    "WitnessRunner",
    "WitnessWorker",
    "WitnessChannelProfileExtractor",
    "WitnessTaskResponseExtraction",
    "WitnessTaskResponseExtractor",
    "accept_candidate",
    "archive_candidate",
    "dismiss_candidate",
    "parse_witness_channel_profile_extraction",
    "parse_witness_task_response_extraction",
    "reactivate_candidate",
    "send_private_suggestion",
    "snooze_candidate",
]
